# Generated by Django 3.2.23 on 2023-11-17 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20231116_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio', to='Api.cinemastudio'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='Api.gender'),
        ),
    ]
